# Generated by Django 4.1.3 on 2022-11-21 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("saip_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameParameters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("budget_cap", models.PositiveIntegerField(null=True)),
                ("depreciation", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "GameParameters",
            },
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField(null=True)),
                ("ende", models.DateTimeField(null=True)),
                ("name", models.CharField(max_length=100, null=True)),
                ("turns", models.PositiveIntegerField(null=True)),
                (
                    "admin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parameters",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="saip_api.gameparameters",
                    ),
                ),
            ],
            options={
                "db_table": "Games",
            },
        ),
        migrations.AddField(
            model_name="companies_upgrades",
            name="game",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="saip_api.game",
            ),
        ),
    ]
