# Generated by Django 4.1.3 on 2022-11-21 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("saip_api", "0002_gameparameters_game_companies_upgrades_game"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companies_upgrades",
            name="upgrade",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="saip_api.upgrade",
            ),
        ),
    ]
