name: deploy
on:
  push:
    branches:
      - prod
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
      - name: Deploy backend and frontend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/SAIP
            git pull
            sudo cp apps/saip_be /var/www/ -r
            cd apps/saip-fe
            yarn run build
            sudo cp dist /var/www/ -r
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx

